package com.example.springdemo.students.models;

import javax.persistence.*;

@Entity
@Table
public class Student {

  @Id
  @SequenceGenerator(name = "student_sequence", sequenceName = "student_secuence", allocationSize = 1)
  @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "student_sequence")
  private Long id;
  private String name;
  private String email;

  public Student() {
  }

  public Student(String name, String email) {
    // ID is not necessary as it is automatically generated by postgres
    this.name = name;
    this.email = email;
  }

  public Long getId() {
    return this.id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public String getEmail() {
    return this.email;
  }
}
